### ISSUE TITLE
How to specify project path in configuration project

### ISSUE THREAD

**Issue by pmunts** [AdaCore/gprbuild#103]
I am attempting to use `gprbuild` for cross-compiling, and am having some problems.

This command works:

 `gprbuild --target=aarch64-linux-gnu -p -aP/usr/local/share/libsimpleio-aarch64-linux-gnu test_hello`

And with the `default.cgpr` from my cross-toolchain, this command works: 

`gprbuild -p -aP/usr/local/share/libsimpleio-aarch64-linux-gnu test_hello`

But this command fails, because `gprbuild` chooses my precompiled library project from the native toolchain instead of the cross-toolchain:

`gprbuild -p test_hello`

Is there some way to set the project path in `default.cgpr`?  I tried adding `for Switches (others) use ("-aP/usr/local/share/libsimpleio-aarch64-linux-gnu");` to `package Builder` in `default.cgpr`, but then I get this error:

`gprbuild: -aP/usr/local/share/libsimpleio-aarch64-linux-gnu can only be used on the command line`

**Comment by t-14** [comment]
The prefix for the project path is computed from Compiler'Driver attribute.
