### ISSUE TITLE
Variable Substitution for gprbuild

### ISSUE THREAD

**Issue by MarcelloPresulli** [AdaCore/gprbuild#11]
Hi all,
i use gprbuild for multilanguage programming, especially in C. Sometimes i've the need to get file- or basename of the actual compilation, so that i can access this variable for further use.

For example, if i want to generate an assembler list file (.lst) for every c file, then i have to use the "Wa,-adhlns=basename.lst" option, but it's not possible because i don't get an access for the actual c file ...

So, is it maybe possible to implement such a feature, or have i overseen something ...
Thanks in adavance.

**Comment by t-14** [comment]
Hi Marcello. Thank you for the suggestion, we will consider that. It's not obvious how to express something like that with the current syntax, so probably if we do decide to do that it will be part of a general gpr engine rewrite.

In the meantime, you can resort to a little trickery to get what you want, by defining your own C compiler driver, along these lines:

In your project, add this:

```ada
package Compiler is
   for Driver ("C") use "my_gcc";
end Compiler;
```

my_gcc:

```bash
#!/bin/sh
args=$#
lastarg=${!args}
basename=`basename $lastarg`
gcc $* "-Wa,-adhlns=$basename.lst"
```

**Comment by MarcelloPresulli** [comment]
Okay I understand, thanks for the workaround at least.
