### ISSUE TITLE
Aggregate GPR suppresses Builder'Default_Switches

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/gprbuild#12]
As demonstrated in the attached, an agggregate project suppresses `Builder'Default_Switches`. This isn't mentioned in the documentation.

I'm glad to see that I can put `--create-map-file` in the aggregate GPR's `Builder'Switches (other)`.

[aggregate-gpr-issue.zip](https://github.com/AdaCore/gprbuild/files/442256/aggregate-gpr-issue.zip)

**Comment by t-14** [comment]
This is as documented, see the very end of section [package Builder in aggregate projects](https://github.com/AdaCore/gprbuild/blob/master/doc/gprbuild_ug/gnat_project_manager.rst#package-builder-in-aggregate-projects) :

> For projects that are built through the aggregate mechanism, the package Builder is ignored, except for the Executable attribute which specifies the name of the executables resulting from the link of the main programs, and for the Executable_Suffix.

**Comment by simonjwright** [comment]
So it is. Sorry to have missed it.

A few lines above, in Global_Configuration_Pragmas, it says

> we ignore the package Builder in other aggregate projects and projects

which may be inconsistent?

**Comment by t-14** [comment]
Can you clarify why you say it's inconsistent? Both places say that package Builder is ignored in aggregated projects as far as I can see?

**Comment by simonjwright** [comment]
Under Global_Configuration_Pragmas it says we ignore Builder everywhere except in the main aggregate project (including in non-aggregate projects), whereas actually we do use 'Executable and 'Executable_Suffix in non-aggregate projects with 'Main.

**Comment by t-14** [comment]
Ok, understood, some wordsmithing may indeed be in order.
