### ISSUE TITLE
More helpful message for "warning: unable to locate objcopy"?

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/gprbuild#123]
When issuing `warning: unable to locate objcopy`, GPRBuild message references are confusing or at least not very helpful, for instance:

```
    14. library project Libadalang is
                        |
        >>> warning: unable to locate objcopy
```
or

`gprname-process.adb:63:45: warning: unable to locate objcopy`

Couldn't be a more detailed message about the operation which has produced the warning?

**Comment by t-14** [comment]
Looks like the latter is due to bogus project location at the point this message is generated. Will suppress it.

> Couldn't be a more detailed message about the operation which has produced the warning?

The operation is a check for objcopy, there is nothing more to that. It's not specific to a specific line in the project...

**Comment by Blady-Com** [comment]
I had a look on Check_Objtool function. It's used twice only in an if condition expression, line [2349](https://github.com/AdaCore/gprbuild/blob/master/src/gprbuild-link.adb#L2349):
```
                           if not Check_Objtool
                             (Objcopy_Exec, "objcopy")
                             or else not Check_Objtool
                               (Objdump_Exec, "objdump")
```
1) If objcopy is found then Objcopy_Exec is set by Check_Objtool, but Objcopy_Exec is never used after!?
2) If objcopy is found then the expression after `or else` is not executed thus Objdump_Exec is not set whereas it is used after at line [2494](https://github.com/AdaCore/gprbuild/blob/master/src/gprbuild-link.adb#L2494)!?

Is it expected?

**Comment by t-14** [comment]
This looks extremely suspicious, especially part (2), I agree! Should probably at the very least be just "or". I'll review the code.

**Comment by simonjwright** [comment]
@Blady-Com didn't mention that they're using a Mac, which is why there's no `objcopy`; and in any case the use gprbuild proposes to make of it in building a static SAL is impossible on macOS because mach-o binaries don't support it.
