### ISSUE TITLE
Help wanted "s-imgllli.ali" not found

### ISSUE THREAD

**Issue by Saikatsaha1996** [AdaCore/gprbuild#135]
How do I solve?

Gcc -11
Termux - Android 

![IMG_20230110_122746](https://user-images.githubusercontent.com/72664192/211482893-f2b547ee-76d2-41ec-8a82-98e608bbaab6.jpg)

**Comment by t-14** [comment]
Looks like your installation is inconsistent - most likely you have gathered together libraries precompiled using different compiler versions.
