### ISSUE TITLE
Build failure using bootstrap.sh

### ISSUE THREAD

**Issue by Earnestly** [AdaCore/gprbuild#14]
* gcc 6.2.1
* GNAT 6.2.1 20160830
* Linux 4.7.5

Cloned both gprbuild and xmlada:
```
cd gprbuild
./bootstrap.sh --prefix="$srcdir"/bootstrap --with-xmlada="$srcdir"/xmlada
```

```
gcc -c -I./ -I./src -I./gpr/src -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/sax -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/dom -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/schema -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/unicode -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/input_sources -O -I- /home/earnest/build/store/gprbuild-bootstrap-git/src/gprbuild/src/gprbuild-main.adb
gcc -c -I./ -I./src -I./gpr/src -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/sax -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/dom -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/schema -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/unicode -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/input_sources -O -I- /home/earnest/build/store/gprbuild-bootstrap-git/src/gprbuild/gpr/src/gpr.adb
gcc -c -I./ -I./src -I./gpr/src -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/sax -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/dom -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/schema -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/unicode -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/input_sources -O -I- /home/earnest/build/store/gprbuild-bootstrap-git/src/gprbuild/gpr/src/gpr-conf.adb
gcc -c -I./ -I./src -I./gpr/src -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/sax -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/dom -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/schema -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/unicode -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/input_sources -O -I- /home/earnest/build/store/gprbuild-bootstrap-git/src/gprbuild/gpr/src/gpr-debug.adb
gcc -c -I./ -I./src -I./gpr/src -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/sax -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/dom -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/schema -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/unicode -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/input_sources -O -I- /home/earnest/build/store/gprbuild-bootstrap-git/src/gprbuild/gpr/src/gpr-env.adb
gcc -c -I./ -I./src -I./gpr/src -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/sax -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/dom -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/schema -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/unicode -I/home/earnest/build/store/gprbuild-bootstrap-git/src/xmlada/input_sources -O -I- /home/earnest/build/store/gprbuild-bootstrap-git/src/gprbuild/gpr/src/gpr-err.adb
gpr-conf.adb:1012:28: "Is_Owner_Writable_File" is undefined
gnatmake: "/home/earnest/build/store/gprbuild-bootstrap-git/src/gprbuild/gpr/src/gpr-conf.adb" compilation error
```

**Comment by gingold-adacore** [comment]
You need a more recent version of gnat!

**Comment by pmderodat** [comment]
FYI, the patch that adds Os_Lib.Is_Owner_Writable_File isn’t yet comitted at the FSF. So building the gprbuild’s master branch will not be possible until then.

**Comment by Earnestly** [comment]
I see, the solution is patience then. Thanks

**Comment by DLightstone** [comment]
Until then, which git tag is consistent with the various GPL versions available at
http://libre.adacore.com/download/

Probably a good idea to post those tag identifiers in the build instructions

**Comment by t-14** [comment]
@DLightstone thanks for the suggestion. We need to review on this side how we support publicly available versions.

**Comment by t-14** [comment]
By means of a workaround, replacing "Is_Owner_Writable_File" with "Is_Writable_File" should work. In fact we will probably install this change until at least GPL2017 is out.

**Comment by DLightstone** [comment]
This is a global phenomena. A need for tag identifiers is also present in Couverture. ( Olivier Hainque is aware of the observation).

**Comment by t-14** [comment]
I don't think tags or branches is a viable solution. If there is a separate branch for the public it will certainly stagnate and bit-rot since we don't have resources to keep it in sync. We will just try to do more to ensure the head is backwards compatible with a reasonable selection of public toolchains (and for sure at least with the fsf head!).

**Comment by DLightstone** [comment]
The general public does not get to work from the development CM tip. The GPL versions released to the public are defacto branches (they simply are not called branches)

Without the tag (for software source released via GITHUB) the public will simply have to search for the consistent versions (as I did). This either by trial and error build, or via web search.

**Comment by t-14** [comment]
You won't need tags if the project is compatible with the last GPL release, which is like I said the goal we want to aim for.

**Comment by DLightstone** [comment]
Maintaining project compatibility is a noble goal. When it cannot be achieved, or when compatibility is temporarily violated the tag is the reference point. It is nothing more than that.

**Comment by t-14** [comment]
Sure :) Here however I think it's achievable (the patch is currently on review). The disruptive change is https://github.com/AdaCore/gprbuild/commit/17143e7a34d356d16a2823321e3a5565a918a112 but it's a few months old so I really prefer to not lock the users to such an old version.

**Comment by t-14** [comment]
Should be fixed by 926cbd5116674f3d88334a09a5944afffa846e75.

**Comment by Earnestly** [comment]
Perhaps you missed one?

```
gpr-util.adb:2030:15: "Is_Owner_Writable_File" is undefined
```

**Comment by t-14** [comment]
Argh. Sorry about that. Patch is on review. We are working on setting up a build with GPL2016 on our side to catch this.

**Comment by DLightstone** [comment]
Are you building GNAT GPL2016 from source, or just installing from the binary distribution?

**Comment by t-14** [comment]
It's "software present tense" ATM, but we'll no doubt use the official binary to make sure we are testing exactly what others would download.

**Comment by DLightstone** [comment]
I would hope that the official binary release is installed on a clean machine when the testing is performed. This for purposes of avoiding pollution attributable to previously installed software.

**Comment by t-14** [comment]
I am sure we'll figure it out ;)

**Comment by DLightstone** [comment]
I have no doubt that you will figure it out.

The only reason I mentioned it relates to an observed difficulty building the binaries from source. Some makefile rules appear to be missing. Clearly the binaries were built, so that implies the distribution source was either prepared on the wrong computer, or the distribution was never tested. or my build environment is not consistent to the reference AdaCore build environment.

**Comment by Earnestly** [comment]
I just hope they don't "figure it out" like they figured out traversing `PATH` to find something resembling a C compiler instead of using `cc`, or how they hardcode installation directories because it's "invarient" while still offering `./configure` options to set them.

**Comment by DLightstone** [comment]
Earnestly, 
I suspect the reference to "figure it out" was to a question of testing logistics, rather than product development

**Comment by t-14** [comment]
> I just hope they don't "figure it out" like they figured out traversing PATH to find something resembling a C compiler

@Earnestly while I am pleased that you haven't [given up](https://github.com/AdaCore/gprbuild/issues/2#issuecomment-217859245) after all, but I don't think this kind of tone is very constructive. It is also a bit hurtful given that we've reviewed the build procedure based on **your** feedback.

> while still offering `./configure` options to set them

Not sure what you are referring to, given there is no configure at all anymore.

**Comment by t-14** [comment]
@DLightstone,

> The only reason I mentioned it relates to an observed difficulty building the binaries from source. Some makefile rules appear to be missing.

Are you referring to GNAT GPL2016 or to GPRbuild?

**Comment by DLightstone** [comment]
The reference is to GNAT GPL2016

**Comment by t-14** [comment]
Understood. You should report it using the standard channel then. Let's keep this discussion limited to GPRbuild.

**Comment by DLightstone** [comment]
Earlier I indicated that there may be missing rule in the GANT GPL 2016 source. This is incorrect. 

Somehow I corrupted the source which I was using for my build. 
A build on clean machine was succesful
