### ISSUE TITLE
GFortran driver name probably incorrect

### ISSUE THREAD

**Issue by DLightstone** [AdaCore/gprbuild#15]
In share/gprconfig/fortran.xml I suspect that the driver name generator for GFortran is incorrect
It currently is
------------------------------------------------------------------
   

   <configuration>
     <compilers>
       <compiler name="GFORTRAN" language="Fortran" />
       <compiler name="GCC-MINGW32" language="Fortran" />
     </compilers>
     <config>
   package Naming is
      for Body_Suffix ("Fortran") use ".f";
   end Naming;

   package Compiler is
      for Driver            ("Fortran") use "${PATH(fortran)}gfortran${PREFIX(fortran)}";
      for Leading_Required_Switches ("Fortran") use
         Compiler'Leading_Required_Switches ("Fortran") &amp;
         ("-c", "-fno-underscoring");
      for Include_Path      ("Fortran") use "CPATH";
   end Compiler;
     </config>
   </configuration>
-----------------------------------------------------------

from http://packages.ubuntu.com/trusty/i386/gfortran-powerpc-linux-gnu/filelist
/usr/bin/powerpc-linux-gnu-gfortran
GFORTRAN appears to follow the convention  "${PATH(fortran)}${PREFIX(fortran)}gfortran"

from http://packages.ubuntu.com/trusty/amd64/gfortran-mingw-w64-x86-64/filelist
/usr/bin/x86_64-w64-mingw32-gfortran
GCC-MINGW32 appears to follow the convention  "${PATH(fortran)}${PREFIX(fortran)}gfortran"

**Comment by t-14** [comment]
Thanks for the heads up, this is definitely wrong, and there is also a similar bug in cpp.xml. We will fix.

**Comment by DLightstone** [comment]
just a speculation, but ${PATH(---language----)}${PREFIX(---language----)}
may just be a global necessity (well at least those where cross compilation is a possibility)
that way renaming links to ---language---- will not have to be created. 

Not knowing the cross compiler naming conventions (no guarantee that the GNU gcc conventions are being followed), be other compiler writers, this may be a case by case situation

**Comment by t-14** [comment]
It is indeed a case by case situation (i.e. it's not _universally_ wrong, for example it's correct for the Wind River compilers that follow convention cc-arm and so on). It does look wrong for the FSF distributions however.

**Comment by DLightstone** [comment]
I thought FSF (Free Software Foundation) compilers were all GNU compilers.
I thought the ${PREFIX} naming convention was established by FSF
(that would be consistent with https://gcc.gnu.org/install/specific.html )

**Comment by t-14** [comment]
Yes, we are in violent agreement :) All I am saying is that some compiler providers do not follow this convention.

**Comment by DLightstone** [comment]
understoud

**Comment by t-14** [comment]
Should be fixed now.
