### ISSUE TITLE
No debug when deleting ali file due to checksum mismatch

### ISSUE THREAD

**Issue by LordAro** [AdaCore/gprbuild#151]
There is zero indication in any verbosity mode when gprbuild decides that an ALI file is out of date due to checksum mismatch. If you're reading the log, you can see that the command just "happens" with no indication as to why this is. (Forcing me to add my own debug prints to a custom gprbuild...)

https://github.com/AdaCore/gprbuild/blob/60d9eebf052325f1610e0ec3128e05e8440346b6/gpr/src/gpr-util.adb#L5425-L5431

(Context: A separate issue that I'm still nailing down that appears to have to do with a gnatprep'd spec file appearing with multiple different checksums)

**Comment by Ankyrine** [comment]
Hello,

We are currently in the process of revamping this whole part of our tools, what you are looking for will be inherently part of what we are designing and developing.
We cannot communicate any date for now.

As such, I'm closing the issue.

Best regards
