### ISSUE TITLE
Add .*-linux-gnu- to identify common Linux cross development tool chains

### ISSUE THREAD

**Issue by DLightstone** [AdaCore/gprbuild#16]
in ..... shared/gprconfig/compiler.xml.

" .*-linux-gnu- " probably can be safely added to the following compiler targets
there should be dot star before the first dash

GCC
G++
GCC-ASM
GNAT
G77
GFORTRAN

(and any of the other standard Linux GNU compilers which are intended to be supported)

${PREFIX} would have to be added to the <external> tags associated with the compiler search definition

It definitely allows (on Ubuntu 16.04) powerpc-linux-gnu to be characterized

If you want to cover a bit more
" ._-linux-gnu._\- "

there should be dot star before the two dashes

will probably also work (it may however require changes to the associate target evaluation grep )

**Comment by t-14** [comment]
The knowledge base is now maintained in another github project gprconfig_kb. We will handle it there.
