### ISSUE TITLE
bootstrap.sh fails on openSUSE Linux

### ISSUE THREAD

**Issue by martinvahi** [AdaCore/gprbuild#19]
After fixing the 

    #!/bin/sh

to 

    #!/usr/bin/env sh

the output is

    ts2@linux-0fiz:~/m_local/bin_p/Ada/gprbuild/originaalid/gprbuild$ ./bootstrap.sh --with-xmlada=../../xmlada --prefix=/home/ts2/m_local/bin_p/Ada/gprbuild/originaalid/gprbuild_bootstrap_version
    gcc -c -I./ -I./src -I./gpr/src -I../../xmlada/sax -I../../xmlada/dom -I../../xmlada/schema -I../../xmlada/unicode -I../../xmlada/input_sources -O -I- /opt/2dot7TiB_k8vaketas/ts2/mittevarundatav/_home/m_local/bin_p/Ada/gprbuild/originaalid/gprbuild/src/gprbuild-main.adb
    gpr_build_util.ads:186:11: expression function is an Ada 2012 feature
    gpr_build_util.ads:186:11: unit must be compiled with -gnat2012 switch
    gnatmake: "/opt/2dot7TiB_k8vaketas/ts2/mittevarundatav/_home/m_local/bin_p/Ada/gprbuild/originaalid/gprbuild/src/gprbuild-main.adb" compilation error
    ts2@linux-0fiz:~/m_local/bin_p/Ada/gprbuild/originaalid/gprbuild$ uname -a
    Linux linux-0fiz 3.16.7-48-desktop #1 SMP PREEMPT Wed Oct 26 18:09:22 UTC 2016 (8c027f6) x86_64 x86_64 x86_64 GNU/Linux
    ts2@linux-0fiz:~/m_local/bin_p/Ada/gprbuild/originaalid/gprbuild$ date
    Fri Dec 30 02:45:59 EET 2016
    ts2@linux-0fiz:~/m_local/bin_p/Ada/gprbuild/originaalid/gprbuild$ gcc --version
    gcc (SUSE Linux) 4.8.3 20140627 [gcc-4_8-branch revision 212064]
    Copyright (C) 2013 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    
    ts2@linux-0fiz:~/m_local/bin_p/Ada/gprbuild/originaalid/gprbuild$ gnat --version
    GNAT 4.8.3 20140627 [gcc-4_8-branch revision 212064]
    Copyright 1996-2013, Free Software Foundation, Inc.
    
    List of available commands
    ...

Both, the xmlada and gprbuild sources have been freshly cloned from their GitHub repositories.

**Comment by pmderodat** [comment]
Hi,

Here is a wild guess: I have the feeling that after your shebang change, the bootstrap script does not uses the same compiler as before. Recent compilers (for instance GNAT GPL 2016) use Ada 2012 by default.

You can check which compiler is used just adding the following command after the shebang line in the bootstrap script:

```sh
$ gnatls -v
```
If you don’t have the compiler you expect, then you should check how your `PATH` environment variable is initialized.

Note that the `master` branch for this repository assumes you use at least the latest GPL (2016) of FSF (6.2) compiler release.

**Comment by t-14** [comment]
> GNAT 4.8.3 20140627 [gcc-4_8-branch revision 212064]

This compiler version is simply too old, by at least two years. As stated above you need to use something close to the latest FSF release.
