### ISSUE TITLE
bootstrap.sh install failure on Darwin

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/gprbuild#28]
`bootstrap.sh` (Sierra, Darwin 16.5.0) gets to the point of installation and fails:
```
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
```
Turns out Darwin install doesn't work like that. I got the job done by replacing
```
install -Dm0755 $bin_progs -t "$DESTDIR$prefix$bindir"
```
by
```
mkdir -p "$DESTDIR$prefix$bindir"
install -m0755 $bin_progs "$DESTDIR$prefix$bindir"
```
`man install` is singularly unhelpful on this point, but it looks as though `install -d` is equivalent to `mkdir -p`.

**Comment by t-14** [comment]
Thanks for your report. We implemented it along the lines you've suggested.
