### ISSUE TITLE
library project / Library_Interface withed by c only project

### ISSUE THREAD

**Issue by atupone** [AdaCore/gprbuild#32]
I'm not able to describe clearly the problem.

I have the following:
A project P that is within a library project L.

The P project is only C

The L project is in ada,
Has 
  for Externally_Built use "True";
  for Library_Interface use ("libadalang");

if the P and L project files are on the same directory there is no problem.
If L is in the /usr/share/gpr  it says "libadalang" is not a unit of this project

If I declare P using also Ada there is no problem too.

From my analysis it seems that gprconfig is run too early, only with the "c" languages, because maybe it needs the path to search for l.gpr ?

He needs to find the 
for Language_Kind            ("Ada") use "unit_based";
in the output of gprconfig to pass the checks for the library interface units

**Comment by t-14** [comment]
Alfredo, can you file a reproducer? The context looks a bit too delicate to try to play this by ear.

**Comment by atupone** [comment]
--------p.gpr
with "l";
project P is
   for Languages use ("C");
end P;

---------l.gpr
library project L is
   for Languages use ("Ada");
   for Source_Dirs use ("/usr/include/l/");
   for Library_Dir use "/usr/lib/l.relocatable/";
   for Library_Interface use ("libadalang");
   for Library_Name use "adalang";

   package Naming is
      for body_suffix ("ada") use ".adb";
      for spec_suffix ("ada") use ".ads";
   end Naming;

   for Externally_Built use "True";
end L;

--------------

That work if the file are in the same directory.
Nope if the l.gpr file is in /usr/share/gpr/

**Comment by atupone** [comment]
This file is actually the file /usr/share/gpr/l.gpr 
[l.gpr.txt](https://github.com/AdaCore/gprbuild/files/1459070/l.gpr.txt) 
This file is the file /usr/include/l/libadalang.ads
[libadalang.ads.txt](https://github.com/AdaCore/gprbuild/files/1459078/libadalang.ads.txt)
Next file is on my /home/alfredo/testAda/p.gpr
[p.gpr.txt](https://github.com/AdaCore/gprbuild/files/1459082/p.gpr.txt)

I do now 

gprbuild -P p.gpr

And it gives CONSTRAINT_ERROR

This is gprbuild-gpl-2017 rebuilt here

If I move l.gpr in the same directory it works

------

ps. These files are extract from my tentatives after building libadalang to test using the testsuite

**Comment by atupone** [comment]
It seems it is my fault.
I will reopen if I find something different related to the same subject
