### ISSUE TITLE
Compile using FSF GCC 7

### ISSUE THREAD

**Issue by okellogg** [AdaCore/gprbuild#39]
On attempting to compile gprbuild/master@c758a7f using FSF GCC 7.3.1, I got this error:

```
$ make all
gprbuild -p -m   -j0 -XBUILD=production  gprbuild.gpr -XLIBRARY_TYPE=static -XXMLADA_BUILD=static
Compile
   [Ada]          gprconfig-main.adb
   [Ada]          gprbuild-main.adb
   [Ada]          gprclean-main.adb
   [Ada]          gprinstall-main.adb
   [Ada]          gprslave.adb
   [Ada]          gprname-main.adb
   [Ada]          gprls-main.adb
   [Ada]          gprbind.adb
gpr-names.adb:389:39: prefix of "IMAGE" attribute must be a type
gpr-names.adb:474:39: prefix of "IMAGE" attribute must be a type

   compilation of gprbind.adb failed

gprbuild: *** compilation phase failed
```

The attached patch fixes this problem:

[gprbuild-master-c758a7f-compile-using-fsf-gcc-7.diff.txt](https://github.com/AdaCore/gprbuild/files/2020712/gprbuild-master-c758a7f-compile-using-fsf-gcc-7.diff.txt)

**Comment by okellogg** [comment]
In commit [682e84a](https://github.com/AdaCore/gprbuild/commit/682e84a254a8f4428d23dc6c0e43af8e74dac9ec),  Robin Morier wrote:

> R521-003 Use Value'Img instead of Value'Image.

Thanks.

**Comment by pmderodat** [comment]
Hello @okellogg,

Thank you for reporting this build issue! I hope you can now compile successfully gprbuild.

**Comment by okellogg** [comment]
@pmderodat wrote:

> I hope you can now compile successfully gprbuild.

All fine now.

**Comment by pmderodat** [comment]
Very good, thank you for confirming!
