### ISSUE TITLE
Gprbuild fails on mingw64

### ISSUE THREAD

**Issue by Alex-Gamper** [AdaCore/gprbuild#43]
Hi AdaCore
The non bootstrap build of gprbuild fails on mingw64. Here are the steps to reproduce from a
msys2-mingw64 shell (using current trunk branch for both gprbuild and xmlada)

1) CC=gcc ./bootstrap.sh --prefix=/mingw64
2) build xmlada
   2.1 ./configure --prefix=/mingw64
   2.2 make
   2.3 make install
3) build gprbuild (non bootstrap)
   3.1) make prefix=/mingw64 setup
   3.2) make (FAILS) with below error

gprbuild -p -m   -j0 -XBUILD=production  gprbuild.gpr -XLIBRARY_TYPE=static -XXMLADA_BUILD=static
gprbuild: could not locate library builder "libexec/gprbuild/gprlib"
make: *** [Makefile:95: build] Error 4

Alex

**Comment by Alex-Gamper** [comment]
I found the issue! The bootstrap actually worked ok, as evidenced by the xmlada build!
However I failed to clean the build environment before rebuilding gprbuild using the NON
bootstrap build (the residual artefacts in the build/source directory probably caused issues)

However now that the "_make_" now works, the "_make install_" (i.e. gprinstall fails) since gprinstall
cant find the **exe's** in the relevant directory !

If I rename/remove the ".**exe**" extension from the relevant executables and then run "_make install_"
then it works fine, However I then need to add back the ".**exe**" extension to the relevant executable's
in the installed directories after the install

It seems that the -_-mode=usage_ option does not work correctly under mingw64 ?

Thanks

Alex

**Comment by t-14** [comment]
Try running the following command: `gprconfig --batch --config=ada` and inspect the file `default.cgpr` that it produces - if your toolchain was properly recognized as a windows native one, it should contain

```
   package Builder is
      for Executable_Suffix use ".exe";
   end Builder;
```

- if it doesn't this may mean your toolchain isn't being recognized properly.

**Comment by Alex-Gamper** [comment]
The default.cgpr file does not contain a "Builder" package, however if I add the triplet
x86_64-**w64**-mingw32 to the cross.xml file in $prefix/share/gprconfig directory then
it show up in the default.cgpr file and the subsequent **make install** works fine


Can I suggest that the addition of the x86_64-w64-mingw32 triplet be added to the Cross.xml
file ? This seems to be the default triplet on msys/msys2

```
   <configuration>
     <targets>
       <target name="dotnet" />
       <target name="^.*-pc-mingw32$" />
       **<target name="^.*-w64-mingw32$" />**
     </targets>
     <config>
   package Builder is
      for Executable_Suffix use ".exe";
   end Builder;
     </config>
   </configuration>
```

**Comment by t-14** [comment]
I think it makes sense to just replace "^.*-pc-mingw32$" with "mingw" to catch every variation, I can't think of a toolchain that would contain "mingw" yet not be a windows one. We will do this, reopening.

**Comment by Alex-Gamper** [comment]
Thank you!
