### ISSUE TITLE
C++ code fails under GNAT 2018

### ISSUE THREAD

**Issue by rogermc2** [AdaCore/gprbuild#44]
I am trying build a simple program using GNAT 2018 GPS that involves ImageMagick read functions.
The program builds and runs using Xcode but fails under GNAT 2018.
The problem seems to be associated with the  ImageMagick read functions, most likely string functions involved with the use of the file name.
At one stage I ascertained that a segmentation fault seemed to be caused by a string swap function being called with a null string address.
As I experience no problems with Xcode, I have tried to generate a config file to make GNAT GPS use the llvm (clang and clang++) compilers instead of the gcc compilers but have been unsuccessful in doing so.
I will very much appreciate any assistance in generating a suitable  config file or other advice.

**Comment by t-14** [comment]
I think the following should give what you want: `gprconfig --config=language:c,name:llvm --batch`

**Comment by rogermc2** [comment]
I tried gprconfig --config=language:c,name:llvm --batch
But:
Error: unknown language 'language:c'

**Comment by t-14** [comment]
Instructions implied up-to-date gprbuild. If it's older, use the following switch instead (note: should be upper case actually) `--config=c,,,,LLVM`

Looks like we are missing a line to do the same for C++. Add in compilers.xml in LLVM block the following: `<languages>C++</languages>` - then you should be able to also do `--config=c++,,,,LLVM`

We will add it too.

**Comment by rogermc2** [comment]
I tried a few variations of adding <languages>C++</languages> to the  LLVM block of compilers.xml including <languages>C,C++</languages> as specified by the manual but when I try to compile a C++ file I get
~~~
gprbuild: raised CONSTRAINT_ERROR : gprbuild-compile.adb:3418:74 access check failed
Load address: 0x10aca6000
Call stack traceback locations:
0x10ad0c085 0x10ad11f0c 0x10ad139bf 0x10ad1455c 0x10acb841d 0x10b1c95a1
~~~

**Comment by rogermc2** [comment]
I finally got it to work without adding `<languages>C++</languages>` but by changing
 `     for Driver              ("C++") use "/opt/gnat/2018/bin/g++";`
to
`     for Driver              ("C++") use "/usr/bin/clang";`
in the .cprg file generated by gprconfig.
However, compilation does produce the following warning:
`clang: warning: argument unused during compilation: '-specs=/private/var/folders/q8/7v9djkh9021057yz0yldxvmr0000gn/T/GNAT-TEMP-000002.TMP' [-Wunused-command-line-argument]`

Thanks for your help

**Comment by t-14** [comment]
To use LLVM for C++ you need the latest knowledge base, in particular this patch: eb94de5 - without it it won't work properly (though I can't reproduce the crash).

> I finally got it to work without adding <languages>C++</languages> but by changing

I don't think that's a good idea. You need to have a consistent KB.

**Comment by rogermc2** [comment]
I agree that changing the config file is not a good idea but its the only solution that I've got at the moment.
Is it possible for me to obtain the latest knowledge base or implement the patch?
Thanks

**Comment by t-14** [comment]
> Is it possible for me to obtain the latest knowledge base

It's this repository ;) (share/gprconfig subdir)

**Comment by rogermc2** [comment]
I downloaded `gprbuild-master` and copied `share/gprconfig` into my `GNAT/2018/share directory`.
However, when I run `gprconfig` I still only get 
`G++ for C++ in /usr/local/bin/` and `G++ for C++ in /opt/gnat/2018/bin/ version 7.3.1 options for C++`.
Is there something else that I need to do.
Thanks.

**Comment by t-14** [comment]
You still need to apply the aforementioned patch (`<languages>C++</languages>`) on top of it - we said we'll do it but didn't get to it yet.

**Comment by rogermc2** [comment]
I've just manually checked the `gprconfig files` that I downloaded from the `share/gprconfig` subdir against patch `eb94de5` and the files appear to include the patch.
As its a while since I've used the unix patch facility, it would take me a while to refamiliarize myself with checking and applying patches.

**Comment by t-14** [comment]
It's what I was referring to here:

> Looks like we are missing a line to do the same for C++. Add in compilers.xml in LLVM block the following: `<languages>C++</languages>` - then you should be able to also do `--config=c++,,,,LLVM`

We just pushed this change so you can just resync.
