### ISSUE TITLE
Build_Type = Gnatpro ??

### ISSUE THREAD

**Issue by paherbst** [AdaCore/gprbuild#53]
I'm assuming this repo is for the GPL version of gprbuild.

However, gpr/src/gpr-version.ads has this line
Build_Type : constant Gnat_Build_Type := Gnatpro;

Why isn't this GPL?

**Comment by t-14** [comment]
This repo is for all versions. We don't have separate repositories for Pro and Community editions, the sources are just patched on the fly depending on which version we are building (same for version and date BTW). Consider gpr-version.ads as a compilable template rather than real source.

**Comment by simonjwright** [comment]
> the sources are just patched on the fly

I was expecting to see some trace of this in this repo, but not - I suppose it’s some external tool/set of tools?

**Comment by t-14** [comment]
Yes, it's our nightly scripts that do this.
