### ISSUE TITLE
gnat/MANIFEST.GPRBUILD is essentially empty

### ISSUE THREAD

**Issue by jrmarino** [AdaCore/gprbuild#6]
The build instructions cannot work.
The target to copy over gnat sources require a populated MANIFEST.GPRBUILD and none of the sources of gnat are included in that list.

Moreover, the GPL 2016 GPRBuild sources downloaded from AdaCore also feature a truncated MANIFEST and don't included gnat sources which could be used to construct one.

The result is that gprbuild cannot be built per instructions.  I can get a manifest from GPL 2015 version of GPLbuild sources, but I don't know if that is accurate for the current version.

Please advise or better yet, plus update MANIFEST.GPRBUILD to include the sources as I believe their omission is a bug.

**Comment by t-14** [comment]
Thanks for the heads-up, indeed the instructions are obsolete. You don't need gnat sources any longer, gprbuild repo has everything that it needs.

We will correct the README. Just disregard any part of it that suggests you need anything beyond configure+make (apart from xmlada dependency obviously).

**Comment by t-14** [comment]
Last vestiges of external dependencies have now been removed.
