### ISSUE TITLE
Gprbuild licensing issue / question

### ISSUE THREAD

**Issue by Alex-Gamper** [AdaCore/gprbuild#62]
The current licensing for Gprbuild is GPL3, andI don't have a problem with that. However
the Gpbuild git repo also contains/builds libgpr, which is also used by other projects such as 
Gnatcoll and Libadalang, both of which have a "GPL3 Run time exception". So my question/issue is

1) Does using for example Libadalang or Gnatcoll (which have "GPL3 runtime exceptions") from
an application build by FSF Gnat/gcc imply that the application must be GPL3 ? since it ultimately
depends on GPRBUILD which does NOT have the "GPL3 runtime exception" in its current form.

2) Can the "GPL3 with runtime exception" be applied to the whole GPRBUILD git repo ?

3) Alternatively can the GPRBUILD repo be split into 2 projects, one being the libgpr component
and the other being the GPRBUILD application that we all know and love ? With appropriate 
licensing being applied, ie "GPL3 with runtime exceptions" for libgpr and GPL3 for GPRBUILD ?

Thanks

Alex

**Comment by pmderodat** [comment]
Hello Alex,

Even though we have no plans to change the GPLv3 license for GPRbuild itself (i.e. the command-line tooll), the sources of LibGPR are distributed on GitHub under the terms of the GPLv3 license with the Runtime exception. That was already present in LibGPR’s copyright notices, at the top of all its sources files, but we’ll also add a `COPYING.RUNTIME` file to describe this exception in the `gpr` directory, hoping it will clarify the matter.

Thank you for reporting this,

**Comment by Alex-Gamper** [comment]
Hi AdaCore

Thanks for clarifying the runtime exception for the libGPR, and I appreciate your assistance, and I am
ok with your solution.

Alex

**Comment by pmderodat** [comment]
Great, thank you for your feedback! :-)
