### ISSUE TITLE
gprbuild configuration problem

### ISSUE THREAD

**Issue by bcartwri96** [AdaCore/gprbuild#70]
Hi there. I'm new here, and while I've been programming in Ada for a couple of years, I don't know how it's compiled etc.

Installing on a new MBP running MacOS Mojave, with a freshly installed GNAT / GPS env and SPARK too, I get the following error while trying to compile a file:

```
gprbuild -d -P/Users/bencartwright/...subdirs.../token_ring.gpr -XSpecific_build_modes=Development/Users/bencartwright/...same subs.../token_ring.adb
No valid configuration found
Generation of configuration files failed
GNAT-TEMP-000001.TMP:1:01: "project" expected
gprbuild: processing of configuration project "/private/var/folders/ym/rp9y64qs6gj1f59rvm7szcxh0000gn/T/GNAT-TEMP-000001.TMP" failed
[2019-07-31 23:00:12] process exited with status 4, elapsed time: 00.22s
```

I've tried reinstalling and I've scanned the web for helpful hints, yet none have really helpful (apart from one tangentially related one here on this very repo)

Can someone please help me? Many thanks :)

**Comment by t-14** [comment]
Hi. Are you reporting an issue with gprbuild that is bundled with GNAT Community, or you are reporting an issue with gprbuild that you've built yourself?

**Comment by bcartwri96** [comment]
That which is bundled with GNAT community 😄

**Comment by t-14** [comment]
Ok, then this github project is not really the right vehicle for reporting that. All I can say is that such a message indicates that gprconfig cannot find its knowledge base. You can try building gprbuild from this project and see if it works better.

**Comment by bcartwri96** [comment]
Do you happen to know where I can go to receive help with this problem? Many thanks :)
