### ISSUE TITLE
Wish: string and string list indexing and slicing.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/gprbuild#72]
Hello,
Base on a suggestion from Dmitry Kazakov:
I think they could simply implement standard string and string list indexing and slicing. That will cover everything. gprbuild already has the function Split. E.g. Split ("x86_64-linux", "-") will get you ("x86_64", "linux"). Now we need indexing to write:

```
  case Split (TARGET, "-") (1) is
     when "x86_64" =>
        ...
     when "arm" =>
        ...
```
HTH, Pascal.

**Comment by t-14** [comment]
Pascal,

The Split builtin is already implemented in [gpr2](https://github.com/AdaCore/gpr), the new iteration of gpr technology that we are working on. But we don't plan to backport it to gpr1.
