### ISSUE TITLE
Docs makefile broken

### ISSUE THREAD

**Issue by jrmarino** [AdaCore/gprbuild#8]
The "prepare" target can't be accomplished:
```
prepare:
	$(CP) ../gnat/gnu_free_documentation_license.rst share/.
	$(CP) ../gnat/ada_pygments.py share/.
	$(CP) ../gnat/favicon.ico share/.
	$(CP) ../gnat/latex_elements.py share/.
	$(CP) ../gnat/sphinx.sty share/.
```
The reason is that ../gnat directory is now empty, so the copy command fails.
Since "prepare" is a pre-requisite of most targets like "html" and "txt", no docs can be build with the makefile as it is.

**Comment by t-14** [comment]
"prepare" target is no longer necessary and has been removed.
