### ISSUE TITLE
gprbuild bootstrap - missing gprconfig_kb public repository

### ISSUE THREAD

**Issue by steve-cs** [AdaCore/gprbuild#82]
Commit https://github.com/AdaCore/gprbuild/commit/de15c785678e51ee586f643091f1fff303e3812d breaks the bootstrap.sh build as it depends on an external knowledge base and https://github.com/AdaCore/gprconfig_kb doesn't exist yet.

**Comment by t-14** [comment]
That project did in fact exist but was private for a few days while we were setting everything up. It should now be accessible.
