### ISSUE TITLE
On MSYS2, gprconfig fails for i686, but not x86_64

### ISSUE THREAD

**Issue by tom-kacvinsky** [AdaCore/gprbuild#92]
I am using the latest `MSYS2` with the package `mingw-w64-i686-gprbuild-bootstrap-git` (and the similar package for `x86_64`).  The 64-bit version of `gprconfig` does not fail, but the 32-bit version fails with this Ada exception

```using project file gprbuild.gpr
Unexpected exception while parsing knowledge base: raised PROGRAM_ERROR : EXCEPTION_ACCESS_VIOLATION
[C:\msys64\opt\gprbuild\bin\gprconfig.exe]
0x8fd698 schema__date_time__parse_year at ???

Invalid setup of the gprconfig knowledge base
GNAT-TEMP-000057.TMP:1:01: "project" expected
gprbuild: processing of configuration project "C:\msys64\tmp\GNAT-TEMP-000057.TMP" failed
```
I tried building the `gprbuild` project hosted on GitHub.  Same problem.  The interesting this is that when I uninstall the `MSYS2` package and build `gprbuild` from source, bootstrapping `gprbuild` first, the bootstrap version works, but the installed (release) version fails with similar Ada exceptions.

**Comment by Fabien-Chouteau** [comment]
Thank you @tom-kacvinsky I will followup on the [msys2](https://github.com/msys2/MINGW-packages/issues/7133) issue for now.
